config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do 
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]      
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def increment_comments
    post.increment!(:CommentsCounter)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  def increment_likes
    post.increment!(:LikesCounter)
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :CommentsCounter, numericality: { greater_than_or_equal_to: 0 }
  validates :LikesCounter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def update_posts_counter
    author.increment!(:PostsCounter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :PostsCounter, numericality: { greater_than_or_equal_to: 0 }

  def return_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    users_url
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# comments controllere
class CommentsController < ApplicationController
  def new
    @comments = Comment.new
  end

  def create
    @current_post = Post.find(params[:post_id])
    @comments = @current_post.comments.new(comment_params)
    @comments.post_id = @current_post.id
    @comments.author_id = Current.user.id
    if @comments.save
      redirect_to "/users/#{@current_post.author.id}/posts/#{@current_post.id}"
    else
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

# likes controller
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: Current.user.id, post_id: @post.id)

    if @like.save
      redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.comments.includes([:author])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = Current.user.id
    if @post.save
      redirect_to "/users/#{Current.user.id}/posts"
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# comments helper
module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

# likes helper
module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# posts helper
module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# users helpeer
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Authordid:</strong>
    <%= comment.author_id %>
  </p>

  <p>
    <strong>Postid:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>Updateat:</strong>
    <%= comment.updated_at %>
  </p>

  <p>
    <strong>Createdat:</strong>
    <%= comment.created_at %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :authordId, style: "display: block" %>
    <%= form.number_field :authordId %>
  </div>

  <div>
    <%= form.label :postid, style: "display: block" %>
    <%= form.number_field :postid %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :UpdateAt, style: "display: block" %>
    <%= form.datetime_field :UpdateAt %>
  </div>

  <div>
    <%= form.label :CreatedAt, style: "display: block" %>
    <%= form.datetime_field :CreatedAt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheMinimalistPlacee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <% if current_user %>
      <h2 class="mt-3">Welcome <%= current_user.name %></h2>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    <% end %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :AuthorId, style: "display: block" %>
    <%= form.number_field :AuthorId %>
  </div>

  <div>
    <%= form.label :PostId, style: "display: block" %>
    <%= form.number_field :PostId %>
  </div>

  <div>
    <%= form.label :CreatedAt, style: "display: block" %>
    <%= form.datetime_field :CreatedAt %>
  </div>

  <div>
    <%= form.label :UpdatedAt, style: "display: block" %>
    <%= form.datetime_field :UpdatedAt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <p>
    <strong>Authorid:</strong>
    <%= like.author_id %>
  </p>

  <p>
    <strong>Postid:</strong>
    <%= like.post_id %>
  </p>

  <p>
    <strong>Createdat:</strong>
    <%= like.created_at %>
  </p>

  <p>
    <strong>Updatedat:</strong>
    <%= like.updated_at %>
  </p>

</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/posts/index.html.erb
<div class="user_detail_posts">
<% @posts.each do |post| %>
<button><%= link_to user_post_url(id: post.id, user_id:@user.id), class:'nav-link' do%>See Post Details</button>
<% end %>
<p><%= post.title %></p>
<p><%= post.text %></p>
<p><%= @user.name %></p>
<% end %>
<button><%=  link_to "Add New post", new_user_post_path(user_id: @user.id) %> </button>
</div>

app/views/posts/new.html.erb
<div class="form_div">
<%= form_with model: @post, url: user_posts_path do|form| %>
   <div><%= form.text_field :title, placeholder: "Post Title" %></div>
  <div>  <%= form.text_area :text, placeholder: "Post content" %></div>
    <div><%= form.submit "Add Post" %></div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="post_detail">
<p><%= @post.title  %></p>
<p><%= @user.name %></p>
<p><%= @post.LikesCounter %></p>
<p><%= @post.CommentsCounter %></p>

<% @comments.each do |comment| %>
<p><%= comment.text %>  <%= comment.author.name %></p>
<% end %>

<%= form_with model: @comments, url: user_post_comments_path(post_id: @post.id) do |form| %>
<div><%= form.text_area :text, placeholder: "Share your thoughts here." %></div>
<div><%= form.submit 'Add Comment' %></div>
<% end %>

<%= form_with model: @likes, url: user_post_likes_path(post_id: @post.id) do |form| %>
<div><%= form.submit 'Like this Post' %></div>
<% end %>
</div>

app/views/users/index.html.erb
<h1> The Minimalist Place </h1>

<div class="user_div">
<% @users.each do |user| %>
  <%= link_to user_path(id: user.id) do%>
    <div class="user_card">
        <div class="user_photo"><img src="<%= user.photo %>"></div>
        <ul class="user_list">
            <li class="user_name"></li>
            <p><%= user.name %></p>
            <li>Posts: <%= user.PostsCounter %></li>
        </ul>
    </div>
    <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user_detail_div">
    <div class="user_detail_photo"><img src="<%= @user.photo %>"></div>
    <div class="user_detail_name"> <%= @user.name %></div>
    <div class="user_detail_bio"><%= @user.bio %></div>
     <% @user.return_posts.each do |post| %>
        <div>
          <div>
            <h5 ><%= post.title %></h5>
            <p ><%= post.text%></p>
          </div>
        </div>
      <% end %> 
    
</div>
 <button><%= link_to user_posts_url(user_id:@user.id), class:'nav-link' do%> See All Posts</button>
 <% end %>